# NYC Yellow Taxi Data Cleaning

## Import Libraries and Loading Data

In [123]:
import pandas as pd 
import numpy as np

In [124]:
df = pd.read_parquet('/home/sylviecalvaire/nyc-taxi/data/raw/yellow_tripdata_2026-02.parquet') 
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,7,2026-02-01 00:05:57,2026-02-01 00:05:57,1.00,0.94,1.00,N,107,170,1,7.20,0.00,0.50,0.00,0.00,1.00,12.95,2.50,0.00,0.75
1,7,2026-02-01 00:35:58,2026-02-01 00:35:58,1.00,1.93,1.00,N,234,141,1,11.40,0.00,0.50,3.43,0.00,1.00,20.58,2.50,0.00,0.75
2,2,2026-02-01 00:08:41,2026-02-01 00:39:32,1.00,9.99,1.00,N,138,68,1,44.30,6.00,0.50,11.01,0.00,1.00,67.81,2.50,1.75,0.75
3,1,2026-02-01 00:29:06,2026-02-01 00:41:04,0.00,1.70,1.00,N,209,13,1,12.80,4.25,0.50,3.70,0.00,1.00,22.25,2.50,0.00,0.75
4,1,2026-02-01 00:53:52,2026-02-01 01:11:21,0.00,3.70,1.00,N,249,229,1,19.80,4.25,0.50,6.35,0.00,1.00,31.90,2.50,0.00,0.75

## Initial Inspection

In [125]:
pd.set_option("display.float_format", "{:.2f}".format)
df.shape
df.columns
df.info()
df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 3399866 entries, 0 to 3399865
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), str(1)
memory usage: 482.3 MB

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,3399866.00,3399866,3399866,2376549.00,3399866.00,2376549.00,2376549,3399866.00,3399866.00,3399866.00,3399866.00,3399866.00,3399866.00,3399866.00,3399866.00,3399866.00,3399866.00,2376549.00,2376549.00,3399866.00
unique,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,2374445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.88,2026-02-14 17:36:40.561750,2026-02-14 17:54:31.024438,1.23,6.24,5.25,NaN,161.19,160.80,0.82,21.65,1.01,0.49,2.64,0.49,0.95,30.11,2.17,0.14,0.52
min,1.00,2026-01-31 23:31:23,2026-01-31 23:36:52,0.00,0.00,1.00,NaN,1.00,1.00,0.00,-2084.10,-7.50,-0.50,-68.00,-111.79,-1.00,-2088.85,-2.50,-1.75,-0.75
25%,2.00,2026-02-07 16:43:00.250000,2026-02-07 17:00:20,1.00,1.00,1.00,NaN,114.00,107.00,0.00,10.00,0.00,0.50,0.00,0.00,1.00,17.64,2.50,0.00,0.00
50%,2.00,2026-02-14 00:13:50,2026-02-14 00:29:51,1.00,1.80,1.00,NaN,161.00,161.00,1.00,16.30,0.00,0.50,2.00,0.00,1.00,24.00,2.50,0.00,0.75
75%,2.00,2026-02-21 11:12:34,2026-02-21 11:26:33.500000,1.00,3.68,1.00,NaN,233.00,234.00,1.00,27.50,1.00,0.50,3.79,0.00,1.00,35.43,2.50,0.00,0.75
max,7.00,2026-03-01 00:51:48,2026-03-01 23:11:29,9.00,328522.20,99.00,NaN,265.00,265.00,4.00,2084.10,20.71,4.75,500.00,111.79,1.00,2088.85,2.50,26.75,0.75
std,0.70,NaN,NaN,0.63,633.65,19.75,NaN,67.13,71.07,0.68,18.57,1.70,0.10,3.83,2.10,0.25,22.08,0.91,0.52,0.35

## Duplicate Check

In [126]:
df.duplicated().sum()

np.int64(0)

## Missing Values

In [127]:
df.isnull().sum().sort_values(ascending=False)

passenger_count          1023317
congestion_surcharge     1023317
store_and_fwd_flag       1023317
RatecodeID               1023317
Airport_fee              1023317
tpep_dropoff_datetime          0
VendorID                       0
tpep_pickup_datetime           0
DOLocationID                   0
payment_type                   0
trip_distance                  0
PULocationID                   0
extra                          0
fare_amount                    0
mta_tax                        0
tip_amount                     0
improvement_surcharge          0
tolls_amount                   0
total_amount                   0
cbd_congestion_fee             0
dtype: int64

## Filling Missing Data

In [128]:
df["passenger_count"] = df["passenger_count"].fillna(0)
df["store_and_fwd_flag"] = df["store_and_fwd_flag"].fillna("Unknown")
df["RatecodeID"] = df["RatecodeID"].fillna(0)
df["congestion_surcharge"] = df["congestion_surcharge"].fillna(0)
df["Airport_fee"] = df["Airport_fee"].fillna(0)

In [129]:
df["trip_duration_min"] = (
    df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]
).dt.total_seconds() / 60

## Invalid Record Filtering

In [130]:
df = df[df["trip_distance"] > 0]
df = df[df["fare_amount"] > 0]
df = df[df["total_amount"] > 0]
df = df[df["trip_duration_min"] > 0]

## Handle Extreme Outliers

Extreme values were removed from trip distance, fare amount, 
total amount, and trip duration to improve data quality and 
reduce the impact of unrealistic records on analysis.

In [131]:
df[["trip_distance", "fare_amount", "total_amount", "trip_duration_min"]].describe()

       trip_distance  fare_amount  total_amount  trip_duration_min
count     3210284.00   3210284.00    3210284.00         3210284.00
mean            6.54        21.81         30.46              18.13
std           652.09        17.57         20.99              24.41
min             0.01         0.01          1.01               0.02
25%             1.07        10.24         17.70               8.68
50%             1.88        16.30         24.00              14.20
75%             3.82        27.50         35.34              22.37
max        328522.20      2084.10       2088.85            6335.87

In [132]:
df[df["trip_distance"] > 100][
    ["trip_distance", "fare_amount", "total_amount", "trip_duration_min"]
].sort_values("trip_distance", ascending=False).head(10)

         trip_distance  fare_amount  total_amount  trip_duration_min
3101390      328522.20        31.11         35.86              22.00
3333779      298292.14        74.10         75.60              46.00
3098086      240830.74        15.07         20.57               3.00
2462915      237905.70        44.19         48.94              39.00
3251056      197869.50        22.13         31.88              18.00
3234539      197805.79        42.96         52.48               6.00
3304668      196820.96        29.96         39.91              21.00
3023991      194203.58        55.41         67.62              38.00
2458929      192007.27        21.65         29.29              11.00
3377840      190858.87        14.84         19.59              16.00

In [133]:
df[df["fare_amount"] > 200][
    ["trip_distance", "fare_amount", "total_amount", "trip_duration_min"]
].sort_values("fare_amount", ascending=False).head(10)

         trip_distance  fare_amount  total_amount  trip_duration_min
1912110          41.62      2084.10       2088.85            2868.52
1875827         221.27      1562.60       1580.14             226.60
9764             17.67      1284.70       1290.45            1778.80
446937          130.27       940.30        957.84             173.13
3200654         251.64       880.56        902.10             267.22
1912279          56.86       878.00        882.00            1091.77
1920012          51.28       850.70        857.20            1046.18
941328          126.11       834.60        842.27             159.32
3223780         260.11       824.83       1006.36             291.88
1084524         475.53       800.00        801.00             586.35

In [134]:
df[df["total_amount"] > 200][
    ["trip_distance", "fare_amount", "total_amount", "trip_duration_min"]
].sort_values("total_amount", ascending=False).head(10)

         trip_distance  fare_amount  total_amount  trip_duration_min
1912110          41.62      2084.10       2088.85            2868.52
1875827         221.27      1562.60       1580.14             226.60
9764             17.67      1284.70       1290.45            1778.80
3223780         260.11       824.83       1006.36             291.88
446937          130.27       940.30        957.84             173.13
3200654         251.64       880.56        902.10             267.22
1912279          56.86       878.00        882.00            1091.77
1920012          51.28       850.70        857.20            1046.18
941328          126.11       834.60        842.27             159.32
2813727         167.08       674.75        809.80             222.67

In [135]:
df = df[df["trip_distance"] <= 100]
df = df[df["fare_amount"] <= 500]
df = df[df["total_amount"] <= 500]
df = df[df["trip_duration_min"] > 0]
df = df[df["trip_duration_min"] <= 300]

In [136]:
df[["trip_distance", "fare_amount", "total_amount", "trip_duration_min"]].describe()

       trip_distance  fare_amount  total_amount  trip_duration_min
count     3208998.00   3208998.00    3208998.00         3208998.00
mean            3.44        21.80         30.45              17.80
std             4.20        17.31         20.76              14.14
min             0.01         0.01          1.01               0.02
25%             1.07        10.23         17.70               8.68
50%             1.88        16.30         24.00              14.18
75%             3.82        27.50         35.34              22.35
max            99.58       499.00        500.00             299.90

## Feature Engineering

In [137]:
df["pickup_hour"] = df["tpep_pickup_datetime"].dt.hour
df["pickup_day_name"] = df["tpep_pickup_datetime"].dt.day_name()
df["pickup_day_of_week"] = df["tpep_pickup_datetime"].dt.dayofweek
df["pickup_month"] = df["tpep_pickup_datetime"].dt.month
df["fare_per_mile"] = df["fare_amount"] / df["trip_distance"]

In [138]:
df = df.replace([np.inf, -np.inf], np.nan)
df.isnull().sum().sort_values(ascending=False)

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
cbd_congestion_fee       0
trip_duration_min        0
pickup_hour              0
pickup_day_name          0
pickup_day_of_week       0
pickup_month             0
fare_per_mile            0
dtype: int64

## Review the Cleaned Dataset

In [139]:
df.head()
df.info()
df[["trip_distance", "fare_amount", "total_amount", "trip_duration_min", "fare_per_mile"]].describe()

<class 'pandas.DataFrame'>
Index: 3208998 entries, 2 to 3399865
Data columns (total 26 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
 20  trip_duration_min      float64
 21  pickup_hour            int32
 22  pickup_day_name        str
 23  pickup_day_of_week     int32
 24  pickup_month           int32
 25  fare_per_mile          float64
dtypes: datetime64[us](2), float64(15), int32(6), int64(1), str(2)
memory usage: 618.5 MB

,trip_distance,fare_amount,total_amount,trip_duration_min,fare_per_mile
count,3208998.00,3208998.00,3208998.00,3208998.00,3208998.00
mean,3.44,21.80,30.45,17.80,30.92
std,4.20,17.31,20.76,14.14,285.71
min,0.01,0.01,1.01,0.02,0.00
25%,1.07,10.23,17.70,8.68,5.97
50%,1.88,16.30,24.00,14.18,7.93
75%,3.82,27.50,35.34,22.35,10.59
max,99.58,499.00,500.00,299.90,35000.00

## Save Cleaned Data

In [140]:
df.to_parquet("/home/sylviecalvaire/nyc-taxi/data/processed/yellow_tripdata_2026-02_cleaned.parquet", index=False)

In [141]:
print("Cleaned data saved successfully.")

Cleaned data saved successfully.

## Exploratory Data Analysis

## Visual Analysis
## SQL Analysis
## Power BI Dashboard
## Key Insights